---
- name: Get current server time
  shell: date "+%Y-%m-%d %H:%M:%S"
  register: server_time
  changed_when: false

- name: Provision call to Levcharity Portal API
  uri:
    url: "https://portal.levcharity.com/api/v1/provision"
    method: POST
    headers:
      Content-Type: "application/json"
    body_format: json
    body:
      ip: "{{ ansible_host }}"
      url: "https://{{ item.key }}"
      updated_at: "{{ server_time.stdout }}"
    status_code: 200,201,202,204
    timeout: 30
  register: api_result
  no_log: false
  retries: 3
  delay: 5
  loop: "{{ wordpress_sites | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Display API response (only in verbose mode)
  debug:
    var: api_result
    verbosity: 1
